"""auto-vote

Revision ID: 649a2dfd9ba5
Revises: cd658eb14996
Create Date: 2022-07-27 11:09:07.409611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "649a2dfd9ba5"
down_revision = "cd658eb14996"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "votes",
        sa.Column("users_id", sa.Integer(), nullable=False),
        sa.Column("posts_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["posts_id"], ["posts.posts_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["users_id"], ["users.users_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("users_id", "posts_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("votes")
    # ### end Alembic commands ###
