"""add phone number

Revision ID: bab1b192df72
Revises: 649a2dfd9ba5
Create Date: 2022-07-27 11:19:28.869272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bab1b192df72"
down_revision = "649a2dfd9ba5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
