"""auto_vote

Revision ID: c2ca330523fb
Revises: c350d49a5502
Create Date: 2022-08-23 23:03:24.211834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ca330523fb'
down_revision = 'c350d49a5502'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "votes",
        sa.Column("users_id", sa.Integer(), nullable=False),
        sa.Column("posts_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["posts_id"], ["posts.posts_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["users_id"], ["users.users_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("users_id", "posts_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("votes")
    # ### end Alembic commands ###